"""Adição da coluna telefone

Revision ID: 3160a654a710
Revises: d1da646cbb63
Create Date: 2026-08-18 23:35:21.047300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3160a654a710'
down_revision: Union[str, Sequence[str], None] = 'd1da646cbb63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone', sa.String(length=11), nullable=False))
        batch_op.create_unique_constraint("uq_clientes_telefone", ['telefone'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_constraint("uq_clientes_telefone", type_='unique')
        batch_op.drop_column('telefone')

    # ### end Alembic commands ###
