"""primeira migração

Revision ID: 3f523102f522
Revises: 
Create Date: 2026-08-12 05:47:23.747720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f523102f522'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bancos',
    sa.Column('id_banco', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_banco', sa.String(length=20), nullable=False),
    sa.Column('num_banco', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_banco')
    )
    op.create_table('clientes',
    sa.Column('id_cliente', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('data_nascimento', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_cliente'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('contas',
    sa.Column('id_conta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_banco', sa.Integer(), nullable=False),
    sa.Column('numero_conta', sa.Integer(), nullable=False),
    sa.Column('agencia', sa.Integer(), nullable=False),
    sa.Column('saldo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('limite_especial', sa.Numeric(precision=10, scale=20), nullable=False),
    sa.ForeignKeyConstraint(['id_banco'], ['bancos.id_banco'], ),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_conta'),
    sa.UniqueConstraint('id_cliente'),
    sa.UniqueConstraint('numero_conta')
    )
    op.create_table('movimentacoes',
    sa.Column('id_movimentacao', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_conta', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('data_movimentacao', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_conta'], ['contas.id_conta'], ),
    sa.PrimaryKeyConstraint('id_movimentacao')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimentacoes')
    op.drop_table('contas')
    op.drop_table('clientes')
    op.drop_table('bancos')
    # ### end Alembic commands ###
