"""campo num_banco=True

Revision ID: 3feb8b94d490
Revises: 3160a654a710
Create Date: 2026-08-18 23:58:42.175599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3feb8b94d490'
down_revision: Union[str, Sequence[str], None] = '3160a654a710'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bancos', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_bancos_num_banco'), ['num_banco'])

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_clientes_cpf'), ['cpf'])

    with op.batch_alter_table('contas', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_contas_id_cliente'), ['id_cliente'])
        batch_op.create_unique_constraint(batch_op.f('uq_contas_numero_conta'), ['numero_conta'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_contas_numero_conta'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_contas_id_cliente'), type_='unique')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_clientes_cpf'), type_='unique')

    with op.batch_alter_table('bancos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_bancos_num_banco'), type_='unique')

    # ### end Alembic commands ###
