"""campo nome babco para varchar 30

Revision ID: d1da646cbb63
Revises: 8e0c05296908
Create Date: 2026-08-12 06:14:25.436461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1da646cbb63'
down_revision: Union[str, Sequence[str], None] = '8e0c05296908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bancos', schema=None) as batch_op:
        batch_op.alter_column('nome_banco',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bancos', schema=None) as batch_op:
        batch_op.alter_column('nome_banco',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
